### ISSUE TITLE
Sprint 3: Finish Implementation of Type 2 BQ in Kotlin

### ISSUE THREAD

**Issue by Juanchix** [ISIS3510-MOBILE-T34/SpendiQ_Android#20]

**Comment by Juanchix** [comment]
After the incident with the database, I think all is in order. The UI are too close with the Figma ones. :3

**Comment by J0FR** [comment]
The implementation of the Type 2 Business Question in Kotlin has been successfully completed, and all elements are in order, including the UI alignment with Figma designs. Since everything meets the expected requirements, I will proceed to close this issue.

Great work, @Juanchix!
