### ISSUE TITLE
Sprint 3: Explanation video of connectivity strategies

### ISSUE THREAD

**Issue by Juanchix** [ISIS3510-MOBILE-T34/SpendiQ_Android#21]

**Comment by Juanchix** [comment]
In collab with @NCKDayz, we recorded a couple of videos showing some Eventual connectivity scenarios

**Comment by J0FR** [comment]
Thank you for the collaboration on this! The explanation videos covering connectivity scenarios have been successfully recorded and documented. Since the task is complete and all requirements are met, I am proceeding to close this issue.

Great work, team!
