### ISSUE TITLE
Sprint 3: Creation and implementation of Caching strategies in Kotlin

### ISSUE THREAD

**Issue by Juanchix** [ISIS3510-MOBILE-T34/SpendiQ_Android#23]

**Comment by Juanchix** [comment]
We try to have similarities in terms of the caching strategy used by the iOS team

**Comment by J0FR** [comment]
Thanks for aligning the caching strategy with the approach used by the iOS team! This consistency will help ensure a more unified experience across platforms. If there are any additional updates or adjustments needed, please let me know.

Great work @Juanchix on keeping the strategies in sync!
